# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodieApp-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodieApp-iOS
  pod 'SwiftLint'
  pod 'CountryPickerView'
  pod 'IQKeyboardManagerSwift'
  pod 'GMStepper'
  pod 'SwiftyStarRatingView'

end
